Traceback (most recent call last):
  File "/home/bob/deployments/python-http-server/app.py", line 20, in <module>
    httpd = SocketServer.TCPServer(("", PORT), Handler)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/bob/deployments/python-http-server/app.py", line 20, in <module>
    httpd = SocketServer.TCPServer(("", PORT), Handler)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
killing process: 26611
[Errno 3] No such process
new application started: 26715
Traceback (most recent call last):
  File "/home/bob/deployments/python-http-server/app.py", line 20, in <module>
    httpd = SocketServer.TCPServer(("", PORT), Handler)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 44, in do_GET
    f = self.send_head()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 66, in send_head
    path = self.translate_path(self.path)
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 155, in translate_path
    path = os.getcwd()
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 44, in do_GET
    f = self.send_head()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 66, in send_head
    path = self.translate_path(self.path)
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 155, in translate_path
    path = os.getcwd()
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 44, in do_GET
    f = self.send_head()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 66, in send_head
    path = self.translate_path(self.path)
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 155, in translate_path
    path = os.getcwd()
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 44, in do_GET
    f = self.send_head()
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 66, in send_head
    path = self.translate_path(self.path)
  File "/usr/lib64/python2.7/SimpleHTTPServer.py", line 155, in translate_path
    path = os.getcwd()
OSError: [Errno 2] No such file or directory
127.0.0.1 - - [27/Oct/2018 18:12:07] "GET / HTTP/1.1" 200 -
